# Generated by Django 6.0.4 on 2026-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
