# Generated by Django 6.0.4 on 2026-05-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_problem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
